modLoader = "javafml" #mandatory
loaderVersion = "[28,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL = "https://github.com/gosvoh/GetExpForEverything/issues"
license = "LGPL 2.1"

[[mods]]
modId = "${mod_id}"
displayName = "${mod_name}"
description = "${mod_description}"
version = "${mod_version}"
displayURL = "${mod_url}"
authors = "${mod_author}"
updateJSONURL="${mod_updateurl}"
logoFile="logo.jpeg"

[[dependencies.getexpforeverything]]
modId = "forge"
mandatory = true
versionRange = "[28,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.getexpforeverything]]
modId = "minecraft"
mandatory = true
versionRange = "[1.14,)"
ordering = "NONE"
side = "BOTH"
